In [3]:
import numpy as np

In [2]:
my_list=[1,2,3,4]
np.array(my_list)

array([1, 2, 3, 4])

In [3]:
my_list_two=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list_two)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#shift+tab

In [6]:
np.arange(4,14)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [7]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.arange(30,0,-6)

array([30, 24, 18, 12,  6])

In [1]:
#16:50

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5,9))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((9,9,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
    

In [15]:
np.linspace(0,10,endpoint= False, retstep=True)

(array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
        2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
        5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
        7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]),
 0.2)

In [18]:
np.linspace(0,10,3,retstep=True)

(array([ 0.,  5., 10.]), 5.0)

In [21]:
np.eye(8,k=-1)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.]])

In [23]:
np.random.rand(4,4)

array([[0.85589418, 0.25342857, 0.94811075, 0.99567055],
       [0.38725367, 0.07069704, 0.95953846, 0.51170961],
       [0.66694617, 0.52232848, 0.26832593, 0.97737901],
       [0.54837923, 0.22298026, 0.10962365, 0.81906215]])

In [24]:
np.random.randn() #Standard distribution note

1.5057274720236

In [28]:
3+3+3*np.random.randn(3,3)

array([[ 3.7261603 , -0.12023256, 11.38829529],
       [ 6.72155413,  4.73346617,  3.19250118],
       [ 5.00633128,  5.90820878,  6.0145122 ]])

In [32]:
np.random.randint(0,100,size=20)    ##the size attribute name is optional

array([28, 31, 56, 67, 59, 17, 66, 32, 93, 21, 86, 29, 19,  1,  8, 67, 13,
       93, 36, 82])

In [33]:
np.random.randint(23,46,20)

array([23, 45, 30, 29, 35, 34, 39, 44, 34, 43, 33, 33, 24, 31, 30, 23, 42,
       28, 26, 44])

In [14]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
print(arr.shape)

(25,)


In [ ]:
#twitter docs

In [2]:
np.logspace(0,10,15,base=2,endpoint=False)

array([  1.        ,   1.58740105,   2.5198421 ,   4.        ,
         6.34960421,  10.0793684 ,  16.        ,  25.39841683,
        40.3174736 ,  64.        , 101.59366733, 161.26989439,
       256.        , 406.3746693 , 645.07957755])

In [4]:
np.full((2,4),fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [6]:
print(arr.shape)

(25,)


In [16]:
arr1=arr.reshape(25,1) #25 rows amd 1 column.
print(arr1)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]


In [19]:
arr2=arr.reshape(5,5) #has  to be factor of  25
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [21]:
rndarr=np.random.randint(1,20,10)
print(rndarr)

[16  3 12 13 17  4  2 15  5  8]


In [25]:
rndarr.max()
rndarr.argmax() #returns the index
rndarr.min()
rndarr.argmin()

6

In [27]:
arrnew=np.arange(0,25)
print(arrnew)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [30]:
arrnew[7]
arrnew[1:5]
arrnew[0:5]

array([0, 1, 2, 3, 4])

In [31]:
arrnew[6:9]=69 #BROADCASTING
print(arrnew)

[ 0  1  2  3  4  5 69 69 69  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [35]:
sliceone=arrnew[10:20]
sliceone
sliceone[:]=1020
sliceone #changes also in original array. avoids memory problems.

array([1020, 1020, 1020, 1020, 1020, 1020, 1020, 1020, 1020, 1020])

In [36]:
arrnew

array([   0,    1,    2,    3,    4,    5,   69,   69,   69,    9, 1020,
       1020, 1020, 1020, 1020, 1020, 1020, 1020, 1020, 1020,   20,   21,
         22,   23,   24])

In [38]:
arr_copy=arrnew.copy() #creates a copy.
arr_copy

array([   0,    1,    2,    3,    4,    5,   69,   69,   69,    9, 1020,
       1020, 1020, 1020, 1020, 1020, 1020, 1020, 1020, 1020,   20,   21,
         22,   23,   24])

In [50]:
arrnew2d=np.random.randn(3,3)
arrnew2d

array([[-0.61897772, -0.88606854,  0.0294994 ],
       [-0.06279379,  0.24685661, -2.26066637],
       [-1.30547975,  0.57146248,  1.427967  ]])

In [55]:
arrnew2dA=np.array(([1,2,3],[4,5,6],[7,8,9]))
arrnew2dA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arrnew2dA[0][0]  #0th index 0th element
arrnew2dA[0,0]

1

In [70]:
arrnew2dA[:2,1:] #before comma rows, after comma columms

array([[2, 3],
       [5, 6]])

In [65]:
arrnew2dA[2]

array([7, 8, 9])

In [68]:
arrnew2dA[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
#fancy indexing allows you to select entire rows and columns out of order.
#allows in "any" order

In [6]:
arr2dc=np.zeros((10,10))
arr2dc

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
arr2dc_length=arr2dc.shape[1]
arr2dc_length

10

In [16]:
for  i in range(arr2dc_length):
    arr2dc[i]=i
arr2dc

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [17]:
arr2dc[[2,3,4,5]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [18]:
arr2dc[[2,7,1,3]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [20]:
arrnew=np.arange(69,169)
arrnew

array([ 69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
       121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
       147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
       160, 161, 162, 163, 164, 165, 166, 167, 168])

In [21]:
arrnew>132

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [24]:
boolval=arrnew>132
boolval

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [26]:
arrnew[boolval]

array([133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
       159, 160, 161, 162, 163, 164, 165, 166, 167, 168])

In [27]:
arrnew[arrnew>160]

array([161, 162, 163, 164, 165, 166, 167, 168])

In [28]:
x=150
arrnew[arrnew>x]

array([151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
       164, 165, 166, 167, 168])

In [29]:
#Basic Numpy Operations

In [31]:
arrnew2=np.arange(1,15)
arrnew2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
arr1=arrnew2+arrnew2
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [33]:
arr2=arrnew2*arrnew2
arr2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196])

In [35]:
arr3=arrnew2-arrnew2
arr3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
arr3/arr3 #normally when divided by zero it gives zero error but not in this case.

C:\Users\KIIT\AppData\Local\Temp\ipykernel_11984\3844900078.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr3/arr3


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan])

In [37]:
1/arr3

C:\Users\KIIT\AppData\Local\Temp\ipykernel_11984\1374327335.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr3


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf])

In [39]:
arr2**0.5
#or
np.sqrt(arr2) #nan  for negative numbers.

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.])

In [41]:
np.max(arr2) #same as arr.max() or amax

196

In [43]:
np.sin(arr2)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175,
       -0.99177885, -0.95375265,  0.92002604, -0.62988799, -0.50636564,
        0.99881522, -0.49102159, -0.60199987,  0.93953006])

In [44]:
np.log(arr2)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 , 4.15888308, 4.39444915, 4.60517019,
       4.79579055, 4.9698133 , 5.12989871, 5.27811466])

In [45]:
np.exp(arr2)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 1.90734657e+21, 6.23514908e+27,
       1.50609731e+35, 2.68811714e+43, 3.54513118e+52, 3.45466066e+62,
       2.48752493e+73, 1.32348326e+85])